#!/bin/bash

if [[ $(bspc query --monitors | wc -l) == 1 ]]
then bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d  I II III IV V VI VII
    bspc monitor DP-1 -d VIII IX X
fi

while read -r; do [[ $REPLY ]] && bspc config $REPLY
done << EOF
split_ratio 0.50
border_width 5
window_gap 10
top_padding 20
right_padding 20
bottom_padding 20
left_padding 20

normal_border_color #2b2f4f
focused_border_color #5a1f25
presel_feedback_color #2b2f4f
EOF

bspc rule -a Screenkey manage=off

xset r rate 250 40
sxhkd -c $CFG/sxhkd/sxhkdrc &

# mpv \
#     --loop-file \
#     --scale='oversample' \
#     --no-audio \
#     --no-osc \
#     --no-osd-bar \
#     --wid 0 \
#     "${DOT}/wal/wanella_city.gif" &
