#!/bin/bash

if [[ $(bspc query --monitors | wc -l) == 1 ]]; then
    bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d  I II III IV V VI VII
    bspc monitor DP-1 -d VIII IX X
fi

bspc config split_ratio 0.50
bspc config border_width 5
bspc config window_gap 3
bspc config top_padding 10
bspc config right_padding 10
bspc config bottom_padding 10
bspc config left_padding 10

bspc config normal_border_color '#713326'
bspc config focused_border_color '#b8422e'
bspc config presel_feedback_color '#713326'

bspc rule -a Screenkey manage=off

/sai/dot/wm/bark/bar.sh &
sxhkd -c /sai/dot/wm/bark/sxhkdrc &
feh --no-fehbg --bg-fill /mnt/adinf/img/swang/swang-Heaven\'s\ Peak.jpg
xset r rate 250 40
