#!/bin/bash

sxhkd -c /sai/dot/wm/fut/sxhkdrc &
feh --no-fehbg --bg-fill /mnt/adinf/img/wal/illya_kuvshinov/illum.png
xset r rate 250 40

if [[ $(bspc query --monitors | wc -l) == 1 ]]; then
    bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d  I II III IV V VI VII
    bspc monitor DP-1 -d VIII IX X
fi

bspc config split_ratio 0.50
bspc config border_width 5
bspc config window_gap 3
bspc config top_padding 7
bspc config right_padding 7
bspc config bottom_padding 7
bspc config left_padding 7

bspc config normal_border_color '#370b4c'
bspc config focused_border_color '#5edae1'
bspc config presel_feedback_color '#370b4c'

bspc rule -a Screenkey manage=off
