#!/bin/sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session bspwm -c /sai/dot/wm/fut/bspwmrc
# exec dbus-launch --sh-syntax --exit-with-session bspwm -c /sai/dot/wm/fut/bspwmrc
exec bspwm -c /sai/dot/wm/fut/bspwmrc
